import { JobDTO, UserSession, PlanDTO, UserSubscriptionDetailsDTO } from "@/types/api";

export const MOCK_USER: UserSession = {
  id: "usr_101",
  name: "Alex Morgan",
  email: "alex.morgan@example.com",
  role: "candidate",
  avatar: "A",
  createdAt: new Date().toISOString(),
};

export const MOCK_JOBS: JobDTO[] = [
  {
    id: "1",
    title: "Senior Full Stack Developer",
    company: "Vercel Inc",
    logoBg: "bg-black",
    logoLetter: "V",
    date: "Jun 10",
    jobType: "Full Time",
    location: "Remote",
    salary: "$120,000 - $150,000",
    category: "Technology & Engineering",
    description:
      "Vercel is the platform for frontend developers, providing speed and reliability. You'll architect and build full-stack features across our core product and internal tooling.",
    responsibilities: [
      "Design and implement scalable APIs and frontend components",
      "Collaborate with design and product teams on new features",
      "Lead code reviews and mentor junior engineers",
      "Own deployments and participating in on-call rotation",
    ],
    requirements: [
      "5+ years of full-stack engineering experience",
      "Deep expertise in React, Next.js and Node.js",
      "Experience with PostgreSQL and Redis databases",
      "Strong communication and collaborative skills",
    ],
    niceToHave: [
      "Experience with edge computing and serverless technologies",
      "Open-source contributions in the Next.js or React ecosystems",
      "Kubernetes and Docker containerization experience",
    ],
    perks: [
      "Fully remote",
      "120k-150k salary",
      "Equity package",
      "Unlimited PTO",
      "Home office budget",
      "Annual learning stipend",
    ],
    applicants: [
      { id: "app_1", name: "Nina Petrov", email: "nina@example.com", date: "Jun 12", avatar: "N", color: "bg-pink-500" },
      { id: "app_2", name: "Omar Shaikh", email: "omar@example.com", date: "Jun 12", avatar: "O", color: "bg-orange-500" },
      { id: "app_3", name: "Chen Wei", email: "chen@example.com", date: "Jun 11", avatar: "C", color: "bg-blue-500" },
    ],
    createdAt: "2026-06-10T10:00:00Z",
  },
  {
    id: "2",
    title: "Backend Engineer (Node.js)",
    company: "Stripe",
    logoBg: "bg-indigo-600",
    logoLetter: "S",
    date: "Jun 11",
    jobType: "Full Time",
    location: "Hybrid",
    salary: "$130,000 - $160,000",
    category: "Technology & Engineering",
    description:
      "Stripe builds financial infrastructure for the internet. Join our core payment platform team to build secure, reliable, and high-performance financial APIs that process millions of transactions.",
    responsibilities: [
      "Design and scale Stripe's core payment processing systems",
      "Improve API response latency and distributed database reliability",
      "Maintain strict security standards and PCI compliance",
      "Build developer tools, software development kits (SDKs), and docs",
    ],
    requirements: [
      "4+ years of backend engineering experience",
      "Expertise in Node.js, TypeScript, and database optimization",
      "Strong understanding of distributed systems and message queues",
      "Experience with security protocols and payment APIs",
    ],
    niceToHave: [
      "Experience with Ruby, Go, or Java",
      "Familiarity with financial tech regulations",
      "Active contributor to open-source systems",
    ],
    perks: [
      "Hybrid work schedule",
      "Top tier health insurance",
      "Learning stipend",
      "401k matching",
      "Wellness allowance",
    ],
    applicants: [
      { id: "app_4", name: "Sarah Jenkins", email: "sarah@example.com", date: "Jun 14", avatar: "S", color: "bg-purple-500" },
      { id: "app_5", name: "Lucas Silva", email: "lucas@example.com", date: "Jun 13", avatar: "L", color: "bg-teal-500" },
    ],
    createdAt: "2026-06-11T12:00:00Z",
  },
  {
    id: "3",
    title: "DevOps / Cloud Architect",
    company: "Amazon AWS",
    logoBg: "bg-orange-500",
    logoLetter: "A",
    date: "Jun 12",
    jobType: "Full Time",
    location: "Onsite",
    salary: "$140,000 - $180,000",
    category: "Data & AI",
    description:
      "Architect and automate AWS cloud solutions. Work with enterprise clients and internal teams to design highly available, secure, and cost-effective cloud architectures.",
    responsibilities: [
      "Design infrastructure architecture for enterprise workloads",
      "Automate CI/CD pipelines and infrastructure provisioning using code",
      "Implement zero-trust security controls and automated vulnerability scanning",
      "Monitor latency, throughput, and system health with CloudWatch and OpenTelemetry",
    ],
    requirements: [
      "AWS Certified Solutions Architect Professional",
      "5+ years administering Linux environments and Kubernetes clusters",
      "Expertise in Terraform, Ansible, and GitLab CI / GitHub Actions",
      "Proficiency in Python or Go for infrastructure automation",
    ],
    niceToHave: [
      "Experience with multi-cloud setups (GCP/Azure)",
      "FinOps and cloud cost-optimization certification",
      "Experience with service mesh technologies (Istio/Linkerd)",
    ],
    perks: [
      "Relocation assistance",
      "Stock purchase plan with discount",
      "Comprehensive dental & vision",
      "Annual conference attendance budget",
      "Free onsite meals",
    ],
    applicants: [
      { id: "app_6", name: "Dmitri Volkov", email: "dmitri@example.com", date: "Jun 13", avatar: "D", color: "bg-blue-600" },
      { id: "app_7", name: "Amara Okafor", email: "amara@example.com", date: "Jun 12", avatar: "A", color: "bg-emerald-500" },
    ],
    createdAt: "2026-06-12T09:00:00Z",
  },
  {
    id: "4",
    title: "AI Research Scientist",
    company: "DeepMind",
    logoBg: "bg-blue-600",
    logoLetter: "D",
    date: "Jun 13",
    jobType: "Full Time",
    location: "Hybrid",
    salary: "$160,000 - $220,000",
    category: "Data & AI",
    description:
      "Advance the frontiers of Artificial General Intelligence. Conduct groundbreaking research in transformer models, multimodal reasoning, and reinforcement learning.",
    responsibilities: [
      "Develop novel deep learning architectures and training paradigms",
      "Publish peer-reviewed papers at NeurIPS, ICML, ICLR, and CVPR",
      "Collaborate with engineering teams to scale models to thousands of TPUs/GPUs",
      "Formulate safety, alignment, and interpretability evaluations for frontier models",
    ],
    requirements: [
      "PhD in Computer Science, Machine Learning, Applied Mathematics, or equivalent",
      "Track record of first-author publications at top-tier AI conferences",
      "Deep proficiency in PyTorch, JAX, and distributed training frameworks",
      "Strong mathematical foundations in probability, linear algebra, and optimization",
    ],
    niceToHave: [
      "Experience with sparse mixture-of-experts (MoE) architectures",
      "Expertise in post-training techniques (RLHF, DPO, KTO)",
      "Open-source deep learning framework contributions",
    ],
    perks: [
      "World-class computational compute access",
      "Generous research sabbatical policy",
      "Top-tier compensation and equity grants",
      "Global collaborative lab network",
      "Full family health benefits",
    ],
    applicants: [],
    createdAt: "2026-06-13T14:00:00Z",
  },
  {
    id: "5",
    title: "Product Designer (UI/UX)",
    company: "Figma",
    logoBg: "bg-purple-600",
    logoLetter: "F",
    date: "Jun 10",
    jobType: "Full Time",
    location: "Remote",
    salary: "$100,000 - $130,000",
    category: "Design & Creative",
    description:
      "Help build the future of design tools. You'll lead design efforts for new collaborative features in Figma, shaping how teams design together.",
    responsibilities: [
      "Conduct user research and translate insights into design solutions",
      "Create wireframes, interactive prototypes, and high-fidelity designs",
      "Maintain and expand Figma's design system tokens",
      "Collaborate closely with product managers and developers",
    ],
    requirements: [
      "Portfolio demonstrating clean typography, layout, and visual systems",
      "4+ years of UI/UX design experience, preferably in SaaS",
      "Mastery of Figma",
      "Experience conducting user interviews and usability tests",
    ],
    niceToHave: [
      "Basic understanding of HTML/CSS/JS",
      "Experience designing multiplayer/collaborative tools",
      "Motion design skills",
    ],
    perks: [
      "Fully remote",
      "Figma Pro subscription",
      "Equipment budget",
      "Health and wellness stipends",
      "Generous PTO",
    ],
    applicants: [
      { id: "app_8", name: "Emma Watson", email: "emma@example.com", date: "Jun 11", avatar: "E", color: "bg-red-500" },
      { id: "app_9", name: "John Doe", email: "john@example.com", date: "Jun 12", avatar: "J", color: "bg-purple-500" },
    ],
    createdAt: "2026-06-10T11:00:00Z",
  },
  {
    id: "6",
    title: "Brand & Visual Designer",
    company: "Airbnb",
    logoBg: "bg-rose-500",
    logoLetter: "A",
    date: "Jun 11",
    jobType: "Full Time",
    location: "Onsite",
    salary: "$95,000 - $120,000",
    category: "Design & Creative",
    description:
      "Shape how Airbnb tells its story to the world. Design brand campaigns, digital assets, and print materials that communicate our mission of belonging.",
    responsibilities: [
      "Design key visual assets for global brand campaigns",
      "Ensure brand consistency across all marketing touchpoints",
      "Create illustrations, iconography, and typographic layouts",
      "Direct photography and video production style guides",
    ],
    requirements: [
      "Degree in Graphic Design or equivalent experience",
      "3+ years of brand design experience in-house or at agencies",
      "Expertise in Adobe Creative Suite and Figma",
      "Strong storytelling and presentation skills",
    ],
    niceToHave: [
      "Experience with 3D design tools",
      "Illustration and sketch abilities",
      "Motion graphics skills",
    ],
    perks: [
      "Onsite food and drinks",
      "Travel credits ($2000/year)",
      "Beautiful office environment",
      "Comprehensive health plans",
      "Paid volunteer time",
    ],
    applicants: [],
    createdAt: "2026-06-11T15:00:00Z",
  },
];

export const MOCK_PLANS: PlanDTO[] = [
  {
    id: "plan_emp_free",
    code: "EMPLOYER_FREE",
    name: "Employer Starter (Free)",
    description: "Basic hiring capabilities with 1 active job posting.",
    priceInCents: 0,
    currency: "USD",
    billingInterval: "MONTHLY",
    targetAudience: "EMPLOYER",
    isActive: true,
    maxActiveJobs: 1,
    maxApplicationsPerMonth: null,
    aiScreeningEnabled: false,
    featuredJobPlacement: false,
    unmaskedApplicantProfiles: false,
    unlimitedCvTemplates: false,
    consultationDiscountPercent: 0,
  },
  {
    id: "plan_emp_starter",
    code: "EMPLOYER_STARTER",
    name: "Employer Growth",
    description: "Growing teams with 3 active job slots and AI screening credits.",
    priceInCents: 2900,
    currency: "USD",
    billingInterval: "MONTHLY",
    targetAudience: "EMPLOYER",
    isActive: true,
    maxActiveJobs: 3,
    maxApplicationsPerMonth: null,
    aiScreeningEnabled: true,
    featuredJobPlacement: false,
    unmaskedApplicantProfiles: true,
    unlimitedCvTemplates: false,
    consultationDiscountPercent: 10,
  },
  {
    id: "plan_emp_pro",
    code: "EMPLOYER_PRO",
    name: "Employer Pro",
    description: "Professional hiring pipeline with 10 active jobs and unlimited AI screening.",
    priceInCents: 7900,
    currency: "USD",
    billingInterval: "MONTHLY",
    targetAudience: "EMPLOYER",
    isActive: true,
    maxActiveJobs: 10,
    maxApplicationsPerMonth: null,
    aiScreeningEnabled: true,
    featuredJobPlacement: true,
    unmaskedApplicantProfiles: true,
    unlimitedCvTemplates: false,
    consultationDiscountPercent: 20,
  },
  {
    id: "plan_emp_ent",
    code: "EMPLOYER_ENTERPRISE",
    name: "Employer Enterprise",
    description: "Unlimited job postings, dedicated support, and full applicant profile visibility.",
    priceInCents: 19900,
    currency: "USD",
    billingInterval: "MONTHLY",
    targetAudience: "EMPLOYER",
    isActive: true,
    maxActiveJobs: null,
    maxApplicationsPerMonth: null,
    aiScreeningEnabled: true,
    featuredJobPlacement: true,
    unmaskedApplicantProfiles: true,
    unlimitedCvTemplates: false,
    consultationDiscountPercent: 30,
  },
  {
    id: "plan_cand_free",
    code: "CANDIDATE_FREE",
    name: "Candidate Basic",
    description: "Standard job application access with 5 monthly submissions.",
    priceInCents: 0,
    currency: "USD",
    billingInterval: "MONTHLY",
    targetAudience: "CANDIDATE",
    isActive: true,
    maxActiveJobs: null,
    maxApplicationsPerMonth: 5,
    aiScreeningEnabled: false,
    featuredJobPlacement: false,
    unmaskedApplicantProfiles: true,
    unlimitedCvTemplates: false,
    consultationDiscountPercent: 0,
  },
  {
    id: "plan_cand_pro",
    code: "CANDIDATE_PRO",
    name: "Candidate Premium Career",
    description: "Unlimited job applications, premium CV templates, and consultation discounts.",
    priceInCents: 1500,
    currency: "USD",
    billingInterval: "MONTHLY",
    targetAudience: "CANDIDATE",
    isActive: true,
    maxActiveJobs: null,
    maxApplicationsPerMonth: null,
    aiScreeningEnabled: true,
    featuredJobPlacement: false,
    unmaskedApplicantProfiles: true,
    unlimitedCvTemplates: true,
    consultationDiscountPercent: 20,
  },
];

export const MOCK_SUBSCRIPTION_DETAILS: UserSubscriptionDetailsDTO = {
  subscription: {
    id: "sub_mock_1",
    userId: "usr_101",
    planId: "plan_emp_pro",
    status: "ACTIVE",
    stripeCustomerId: "cus_mock_123",
    stripeSubscriptionId: "sub_mock_123",
    currentPeriodStart: new Date(Date.now() - 5 * 86400000).toISOString(),
    currentPeriodEnd: new Date(Date.now() + 25 * 86400000).toISOString(),
    cancelAtPeriodEnd: false,
    canceledAt: null,
    trialEndsAt: null,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  plan: MOCK_PLANS[2],
  status: "ACTIVE",
  isPaidActive: true,
  cancelAtPeriodEnd: false,
  currentPeriodEnd: new Date(Date.now() + 25 * 86400000).toISOString(),
  usage: {
    jobsPostedCount: 2,
    applicationsCount: 0,
    aiScreeningsCount: 8,
  },
  effectiveLimits: {
    maxActiveJobs: 10,
    maxApplicationsPerMonth: null,
    aiScreeningEnabled: true,
    featuredJobPlacement: true,
    unmaskedApplicantProfiles: true,
    unlimitedCvTemplates: false,
    consultationDiscountPercent: 20,
  },
};
